### ISSUE TITLE
Are PA0/PA1/PA10 bridged together?

### ISSUE THREAD

**Issue by motla** [aleksandrgilfanov/stm32-dmx-receiver#1]
Hi,
Thanks for sharing your code. It's very mighty and unfortunately there are not many recent resources out there to start developing using DMX on STM32.
I will try to use the same approach using an UART/Timer combination.
If I understand correctly, the two timer channels TIM2_CH1, TIM2_CH2 (PA0, PA1) are bridged together with the USART1_RX (PA10) in your hardware?
Thanks

**Comment by aleksandrgilfanov** [comment]
Yes, you are right. Please, note that this code is not well tested... Currently I am not using timers at all, and it looks much more stable and simplier. You can check this approach here: https://github.com/aleksandrgilfanov/dmx8x8a

**Comment by motla** [comment]
Ok. I will try to commute Timer and UART alternate functions on the same RX line by reconfiguring the GPIO. In this way I may be able to discredit wrong break conditions.
Thanks a lot for your help!
